// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrwroFHqJCv87iU3g5N0uCKIHljZ_7Vp8',
    appId: '1:35111375046:web:a216bdfefb896fc5dd47c7',
    messagingSenderId: '35111375046',
    projectId: 'appchay-28be9',
    authDomain: 'appchay-28be9.firebaseapp.com',
    storageBucket: 'appchay-28be9.firebasestorage.app',
    measurementId: 'G-LGVH3Z1C3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJMaUEFKC1my0wuAPJ6to69d-c0xptaA',
    appId: '1:35111375046:android:874a62f847f092a8dd47c7',
    messagingSenderId: '35111375046',
    projectId: 'appchay-28be9',
    storageBucket: 'appchay-28be9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXMv4iCfBp9dy5VETn3YCOCHQzYBGHuYM',
    appId: '1:35111375046:ios:e6fd32910e93db8fdd47c7',
    messagingSenderId: '35111375046',
    projectId: 'appchay-28be9',
    storageBucket: 'appchay-28be9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXMv4iCfBp9dy5VETn3YCOCHQzYBGHuYM',
    appId: '1:35111375046:ios:e6fd32910e93db8fdd47c7',
    messagingSenderId: '35111375046',
    projectId: 'appchay-28be9',
    storageBucket: 'appchay-28be9.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrwroFHqJCv87iU3g5N0uCKIHljZ_7Vp8',
    appId: '1:35111375046:web:d3e5f34d5098e48cdd47c7',
    messagingSenderId: '35111375046',
    projectId: 'appchay-28be9',
    authDomain: 'appchay-28be9.firebaseapp.com',
    storageBucket: 'appchay-28be9.firebasestorage.app',
    measurementId: 'G-27HXNPG08J',
  );
}
